name: Deploy MkDocs

on:
  push:
    branches:
      - main  # Change to your default branch if it's not 'main'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x  # Specify the Python version you want to use
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: |
          python -m pip install --upgrade pip
          
      - run: pip install mkdocs mkdocs—material
      - run: |
          cd docs
          mkdocs build -f mkdocs.yml
          mkdocs gh-deploy --force
        


#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install mkdocs mkdocs-material

#       - name: Build MkDocs site
#         run: mkdocs build -f docs/mkdocs.yml

#       - name: Deploy to GitHub Pages
#         run: |
#           cd docs
#           mkdocs gh-deploy --force
        


# name: ci
# on:
# push:
# branches:
# — master
# — main
# permissions:
# contents: write
# jobs:
# deploy:
# runs—on: ubuntu—latest
# steps:
# — uses: actions/checkout@v3
# — uses: actions/setup—python@v4
# with:
# python—version: 3. x
# r— uses: actions/cache@v2
# with:
# key: ${{ github. ref } }
# path: . kachel
# — run: pip install mkdocs—material
# run: mkdocs gh-deploy
# ——force