name: Docker Image CI

on:
  push:
    branches:
      - main 

permissions:
  contents: write

jobs:
  Builddocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x  
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: |
          python -m pip install --upgrade pip

      - run: pip install mkdocs
      - run: |
          cd docs
          mkdocs build -f mkdocs.yml
          mkdocs gh-deploy --force

  
  push_to_registry:
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out the repo
        uses: actions/checkout@v3
  
      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Login to docker hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Extract metadata (tags,labels) for docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  
  Continuous-Deployment:
    needs: push_to_registry
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull images
        run: |
        
      - name: Run Docker Image to serve users
        run: |
         docker run -d -p 8501:8501 --name=stapp -e 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}' -e 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}' -e 'AWS_REGION=${{ secrets.AWS_REGION }}'  ${{secrets.REGISTRY}}/${{ secrets.IMAGE_NAME }}:main
      - name: Clean previous images and containers
        run: |
         docker system prune -f


















  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: DockerHub Login
  #       env:
  #         DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  #         DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}} 
  #       run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  #     - name: Build the Docker image
  #       run: docker build -t cicd
  #     - name: Push to DockerHub
  #       run: docker push ravikumar46931/cicd